import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Blogs App',
  description: 'Generated by create next app',
};

const NavBar = () => {
  return (
    <nav className='bg-gray-800 p-4'>
      <div className='container mx-auto flex justify-around'>
        <Link href='/' className='text-white hover:text-gray-300'>
          Home
        </Link>
      </div>
    </nav>
  );
};

export default function RootLayout({
  children,
  params: { lng },
}: Readonly<{
  children: React.ReactNode;
  params: { lng: string };
}>) {
  return (
    <html lang={lng}>
      <body className={inter.className}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
